#3 デフォルトのレイアウト作成
Sato-Eisaku/green-fest-map pull request #4
Opened 2022-06-12 16:19 UTC by Sato-Eisaku

ハンバーガーのアイコンとタイトルの位置関係がうまくいかない。
ハンバーガーは左寄せ、タイトルは中央にしたい。

2022-06-12 17:15 UTC, himantyu-yuma requested changes
レビュー部分の修正と，
`yarn lintfix`
の実行をお願いします

2022-06-12 17:15 UTC, himantyu-yuma commented on src/layouts/default.vue
> +          </v-list-item>
全ての構成要素が同じなので，script側で
```[vue]
data: () => ({
  navItems: [
    {
      icon: mdi-map-search,
      title: マップ
    }
  ]
})
```
みたいにデータを用意して，
```[vue]
          <v-list-item v-for="item in navItems">
            <v-list-item-icon>
              <v-icon>{{ item.icon }}</v-icon>
            </v-list-item-icon>
            <v-list-item-title>{{ item.title }}</v-list-item-title>
          </v-list-item>
```
とかにした方がスマートだね（OAOO原則に則れば）

最初から↑のパターンで書こうというよりは，「ここまとめられそうじゃね？」みたいなところを見つけたらまとめようくらいのノリでいいと思います！（過度にまとめすぎるのも良くないので，そこらへんの匙加減は徐々に身に着けていけるといいかな～って感じです）

2022-06-12 22:48 UTC, Sato-Eisaku commented on src/layouts/default.vue
> +          </v-list-item>
詳細にレビューしていただきありがとうございます！
僕ももっと詳細に書けばよかったです…

`yarn lintfix`インストールしました。
まとめた方が良いのはその通りなので、まとめます！！
改善点挙げていただけるのめちゃめちゃ助かります！！

あと、プルリクエストの使い方間違えてしまいました…
できないことはissueに書くべきでした！

2022-06-12 22:50 UTC, Sato-Eisaku commented
詳細にレビューしていただきありがとうございます！
僕ももっと詳細に書けばよかったです…

`yarn lintfix`インストールしました。
まとめた方が良いのはその通りなので、まとめます！！
改善点挙げていただけるのめちゃめちゃ助かります！！

あと、プルリクエストの使い方間違えてしまいました…
できないことはissueに書くべきでした！

2022-06-13 02:28 UTC, himantyu-yuma commented
あ，なるほどｗ

GitHub上からissueにコメントつけられるのでそこに書くといいかも？
聞きたいことあれば @Sato-Eisaku みたいにメンション飛ばしてもらえれば早く気付けるはず
（私もあまり仕様を理解していないので探り探りやっていこう）

2022-06-16 17:15 UTC, himantyu-yuma approved these changes
修正確認しました！
コメントも追記されていていいですね 👍

2022-06-16 17:36 UTC, himantyu-yuma commented on src/layouts/default.vue
> +      </v-container>
多分 `v-app-bar-nav-icon` と `v-toolbar-title` を `v-container` から出せばやりたいこと出来る気がする？

↓こうすれば多分いける
```[vue]
    <v-app-bar
      color="light-green"
      dark
      dence
      collapse-on-scroll
      app
    >
      <v-app-bar-nav-icon @click="drawer = true" />
      <v-toolbar-title class="flex text-center">
        緑丘祭非公式アプリ
      </v-toolbar-title>
    </v-app-bar>
```
基本的にコンテナはhtmlで言うとmainタグとかにあたる場所に使うもので，
そこに適用されたときに真価を発揮するようになっているのであまりヘッダーやフッターでは使わないかな？

コンテナの左右にマージンが設定されていたり，コンテナ内部に特殊なCSSが適用されたりしているので，
ちょっと隙間が空いたり，上下中央揃えにならないのはそこらへんが原因かな～と思います．

ただ実際に試行錯誤したのはめっちゃいいです！
↑みたいなのは結構経験則で，実際にやってみないと分からなかったりしますし，
こういう方法もあるよ～とか，一般的にはこうだよみたいな話は気付き次第随時していくので，
あまり気にせず思いついたこと色々やってみてください！

実際に自分で考えてやったことに対してコメントを貰う方が参考になるかな～とも思うので．

2022-06-18 14:14 UTC, Sato-Eisaku commented on src/layouts/default.vue
> +      </v-container>
うわあああありがとうございます🙇‍♂️🙇‍♂️
とても参考になります！！
v-containerよくわからずに使っていたので…

コード直しましたが、タイトルがやはりちょうど真ん中に来ません…（以下の画像の通りです）

![image](https://user-images.githubusercontent.com/79731074/174442161-62942b7a-f344-4775-8399-95cd76d76e87.png)

全体の横幅に対して、タイトルを中央に持っていきたいです！！

2022-06-18 15:14 UTC, merged